### ISSUE TITLE
Request treshold setting doesnt match the signal output

### ISSUE THREAD

**Issue by tblaznik** [Sharparam/cybersyn-combinator#40] opened 2024-10-30 22:23 UTC
### Description

I set the request treshold on one of my combinators to 8000. The output signal was not the expected 8000 but 16000 instead.
![image](https://github.com/user-attachments/assets/38fcf3c0-bacd-412b-bd72-7c2fda0eec9a)

I tried resetting it to default, which is 2000. This outputs 8000. 
![image](https://github.com/user-attachments/assets/23e67ef1-bc8f-4699-a260-bec43b00a380)

### Expected behaviour

I expected the output signal to be the same as the value set in the combinator.

### Actual behaviour

The values seem to be multiplied by either 2 or 4. Not sure what could be affecting this, the other two settings on the combinator are both 0.

### Steps to reproduce

Build a combinator, check the output signal.
I built this from a blueprint that i first created in the "Blueprint sandboxes" mod, but that shouldnt cause any issues.
I also tried deleting and rebuilding the combinator, same results.

### Mod version

2.1.3

### Factorio version

2.0.12

### Operating system

win64

**Comment by Sharparam** [comment] 2024-10-31 02:52
Hm, this sounds like there's an extra "hidden" request threshold signal in it set to 8000 for some reason.

Does it disappear if you hover the combinator with your mouse and run the command `/cc_sort`?

I'll have to investigate if something weird happens with signals and/or logistic groups when building from blueprints.

Did the combinator in the blueprint have a non-default threshold set?

**Comment by tblaznik** [comment] 2024-10-31 10:26
Hey,

I think youre right, i set the treshold in the blueprints to 8000, and that must have been the hidden request that was overriding everything.

I tried the command with just hovering, and it did nothing, but when i actually clicked on it an ran it, the treshold was fixed and got updated correctly.

I also tried to do some more testing by building the blueprint, but i cant reproduce the bug today. This was after running the /cc_sort, so maybe that was what fixed it.

**Comment by Sharparam** [comment] 2024-11-13 20:35
The latest version (v2.2.3) has some updated logic for signal validation now, which should be better in cleaning up the special CS signals and detecting if there are duplicates.

Not sure how to reliably reproduce the situation to see if this fixes it though.

**Comment by Sharparam** [comment] 2024-11-22 10:34
I'll close this since the v2.2.3 update should fix the issue. If it still happens, feel free to re-open!

**Closed by Sharparam** 2024-11-22 10:34 UTC
Labels: bug
