### ISSUE TITLE
[CRASH] Error MainLoop.cpp:1382: Exception at tick 96680581: Мод Cybersyn Combinator (0.6.1)

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Sharparam/cybersyn-combinator#32] opened 2023-08-09 15:07 UTC
```
23824.218 Error MainLoop.cpp:1382: Exception at tick 96680581: Мод Cybersyn Combinator (0.6.1) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event cybersyn-combinator::on_gui_text_changed (ID 2)
__cybersyn-combinator__/scripts/gui.lua:506: attempt to perform arithmetic on field 'stack_size' (a nil value)
stack traceback:
	__cybersyn-combinator__/scripts/gui.lua:506: in function 'handler'
	__flib__/gui-lite.lua:169: in function <__flib__/gui-lite.lua:152>
23824.218 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "Мод Cybersyn Combinator (0.6.1) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event cybersyn-combinator::on_gui_text_changed (ID 2)
__cybersyn-combinator__/scripts/gui.lua:506: attempt to perform arithmetic on field 'stack_size' (a nil value)
stack traceback:
	__cybersyn-combinator__/scripts/gui.lua:506: in function 'handler'
	__flib__/gui-lite.lua:169: in function <__flib__/gui-lite.lua:152>"
```

**Comment by Sharparam** [comment] 2023-08-09 16:06
Hm, some kind of item that doesn't have a stack size? Do you have some steps to reproduce?

**Comment by mayorovp** [comment] 2023-08-09 16:55
Possible steps:

1, lag the server (by placing >10000 ghosts for construction bots)
2. open combinator ui
3. add some item request and press green button
5. while the request is creating edit it and press green button again

**Comment by Sharparam** [comment] 2023-08-09 19:31
I can't seem to recreate it, but I added some checks and logging that will try to recover if possible in latest commit, you can get the zipped zip here: https://github.com/Sharparam/cybersyn-combinator/suites/14962593033/artifacts/853413681

If it manages to recover a stack size it will log a warning, otherwise an error. Can you try with that version and see if the situation improves?

**Comment by Sharparam** [comment] 2023-08-19 22:51
Due to inability to reproduce the issue I'll close this. The fix mentioned above will be part of the next release to the mod portal anyway, as it might improve things if this issue were to happen again.

Feel free to re-open if the situation changes!

**Closed by Sharparam** 2023-08-19 22:51 UTC
